version: '3.4'

services:
  learndocker:
    image: learndocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - DJANGO_USER=${DJANGO_USER}
      - DJANGO_PASSWORD=${DJANGO_PASSWORD}
      - DJANGO_HOST=db:5432
    depends_on:  # Ensure db starts before learndocker
      - db

  db:
    image: postgres:14.5
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: