version: '3.4'

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - IS_DOCKER=true 
    ports:
      - "5433:5432"

  learndocker:
    image: learndocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

    depends_on:  # Ensure db starts before learndocker
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - IS_DOCKER=true
